/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package repositories;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Shipment extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Shipment\",\"namespace\":\"repositories\",\"fields\":[{\"name\":\"shipmentId\",\"type\":\"string\"},{\"name\":\"pickupPlace\",\"type\":\"string\"},{\"name\":\"deliveryPlace\",\"type\":\"string\"},{\"name\":\"creationTime\",\"type\":\"long\"},{\"name\":\"shipmentNumber\",\"type\":\"string\"},{\"name\":\"transportationMode\",\"type\":\"string\"},{\"name\":\"shipmentTrackingStatus\",\"type\":\"string\"},{\"name\":\"edd\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"completionTime\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"externalShipmentId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"shipmentType\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence shipmentId;
  @Deprecated public java.lang.CharSequence pickupPlace;
  @Deprecated public java.lang.CharSequence deliveryPlace;
  @Deprecated public long creationTime;
  @Deprecated public java.lang.CharSequence shipmentNumber;
  @Deprecated public java.lang.CharSequence transportationMode;
  @Deprecated public java.lang.CharSequence shipmentTrackingStatus;
  @Deprecated public java.lang.Long edd;
  @Deprecated public java.lang.Long completionTime;
  @Deprecated public java.lang.CharSequence externalShipmentId;
  @Deprecated public java.lang.CharSequence shipmentType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Shipment() {}

  /**
   * All-args constructor.
   */
  public Shipment(java.lang.CharSequence shipmentId, java.lang.CharSequence pickupPlace, java.lang.CharSequence deliveryPlace, java.lang.Long creationTime, java.lang.CharSequence shipmentNumber, java.lang.CharSequence transportationMode, java.lang.CharSequence shipmentTrackingStatus, java.lang.Long edd, java.lang.Long completionTime, java.lang.CharSequence externalShipmentId, java.lang.CharSequence shipmentType) {
    this.shipmentId = shipmentId;
    this.pickupPlace = pickupPlace;
    this.deliveryPlace = deliveryPlace;
    this.creationTime = creationTime;
    this.shipmentNumber = shipmentNumber;
    this.transportationMode = transportationMode;
    this.shipmentTrackingStatus = shipmentTrackingStatus;
    this.edd = edd;
    this.completionTime = completionTime;
    this.externalShipmentId = externalShipmentId;
    this.shipmentType = shipmentType;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return shipmentId;
    case 1: return pickupPlace;
    case 2: return deliveryPlace;
    case 3: return creationTime;
    case 4: return shipmentNumber;
    case 5: return transportationMode;
    case 6: return shipmentTrackingStatus;
    case 7: return edd;
    case 8: return completionTime;
    case 9: return externalShipmentId;
    case 10: return shipmentType;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: shipmentId = (java.lang.CharSequence)value$; break;
    case 1: pickupPlace = (java.lang.CharSequence)value$; break;
    case 2: deliveryPlace = (java.lang.CharSequence)value$; break;
    case 3: creationTime = (java.lang.Long)value$; break;
    case 4: shipmentNumber = (java.lang.CharSequence)value$; break;
    case 5: transportationMode = (java.lang.CharSequence)value$; break;
    case 6: shipmentTrackingStatus = (java.lang.CharSequence)value$; break;
    case 7: edd = (java.lang.Long)value$; break;
    case 8: completionTime = (java.lang.Long)value$; break;
    case 9: externalShipmentId = (java.lang.CharSequence)value$; break;
    case 10: shipmentType = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'shipmentId' field.
   */
  public java.lang.CharSequence getShipmentId() {
    return shipmentId;
  }

  /**
   * Sets the value of the 'shipmentId' field.
   * @param value the value to set.
   */
  public void setShipmentId(java.lang.CharSequence value) {
    this.shipmentId = value;
  }

  /**
   * Gets the value of the 'pickupPlace' field.
   */
  public java.lang.CharSequence getPickupPlace() {
    return pickupPlace;
  }

  /**
   * Sets the value of the 'pickupPlace' field.
   * @param value the value to set.
   */
  public void setPickupPlace(java.lang.CharSequence value) {
    this.pickupPlace = value;
  }

  /**
   * Gets the value of the 'deliveryPlace' field.
   */
  public java.lang.CharSequence getDeliveryPlace() {
    return deliveryPlace;
  }

  /**
   * Sets the value of the 'deliveryPlace' field.
   * @param value the value to set.
   */
  public void setDeliveryPlace(java.lang.CharSequence value) {
    this.deliveryPlace = value;
  }

  /**
   * Gets the value of the 'creationTime' field.
   */
  public java.lang.Long getCreationTime() {
    return creationTime;
  }

  /**
   * Sets the value of the 'creationTime' field.
   * @param value the value to set.
   */
  public void setCreationTime(java.lang.Long value) {
    this.creationTime = value;
  }

  /**
   * Gets the value of the 'shipmentNumber' field.
   */
  public java.lang.CharSequence getShipmentNumber() {
    return shipmentNumber;
  }

  /**
   * Sets the value of the 'shipmentNumber' field.
   * @param value the value to set.
   */
  public void setShipmentNumber(java.lang.CharSequence value) {
    this.shipmentNumber = value;
  }

  /**
   * Gets the value of the 'transportationMode' field.
   */
  public java.lang.CharSequence getTransportationMode() {
    return transportationMode;
  }

  /**
   * Sets the value of the 'transportationMode' field.
   * @param value the value to set.
   */
  public void setTransportationMode(java.lang.CharSequence value) {
    this.transportationMode = value;
  }

  /**
   * Gets the value of the 'shipmentTrackingStatus' field.
   */
  public java.lang.CharSequence getShipmentTrackingStatus() {
    return shipmentTrackingStatus;
  }

  /**
   * Sets the value of the 'shipmentTrackingStatus' field.
   * @param value the value to set.
   */
  public void setShipmentTrackingStatus(java.lang.CharSequence value) {
    this.shipmentTrackingStatus = value;
  }

  /**
   * Gets the value of the 'edd' field.
   */
  public java.lang.Long getEdd() {
    return edd;
  }

  /**
   * Sets the value of the 'edd' field.
   * @param value the value to set.
   */
  public void setEdd(java.lang.Long value) {
    this.edd = value;
  }

  /**
   * Gets the value of the 'completionTime' field.
   */
  public java.lang.Long getCompletionTime() {
    return completionTime;
  }

  /**
   * Sets the value of the 'completionTime' field.
   * @param value the value to set.
   */
  public void setCompletionTime(java.lang.Long value) {
    this.completionTime = value;
  }

  /**
   * Gets the value of the 'externalShipmentId' field.
   */
  public java.lang.CharSequence getExternalShipmentId() {
    return externalShipmentId;
  }

  /**
   * Sets the value of the 'externalShipmentId' field.
   * @param value the value to set.
   */
  public void setExternalShipmentId(java.lang.CharSequence value) {
    this.externalShipmentId = value;
  }

  /**
   * Gets the value of the 'shipmentType' field.
   */
  public java.lang.CharSequence getShipmentType() {
    return shipmentType;
  }

  /**
   * Sets the value of the 'shipmentType' field.
   * @param value the value to set.
   */
  public void setShipmentType(java.lang.CharSequence value) {
    this.shipmentType = value;
  }

  /** Creates a new Shipment RecordBuilder */
  public static repositories.Shipment.Builder newBuilder() {
    return new repositories.Shipment.Builder();
  }
  
  /** Creates a new Shipment RecordBuilder by copying an existing Builder */
  public static repositories.Shipment.Builder newBuilder(repositories.Shipment.Builder other) {
    return new repositories.Shipment.Builder(other);
  }
  
  /** Creates a new Shipment RecordBuilder by copying an existing Shipment instance */
  public static repositories.Shipment.Builder newBuilder(repositories.Shipment other) {
    return new repositories.Shipment.Builder(other);
  }
  
  /**
   * RecordBuilder for Shipment instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Shipment>
    implements org.apache.avro.data.RecordBuilder<Shipment> {

    private java.lang.CharSequence shipmentId;
    private java.lang.CharSequence pickupPlace;
    private java.lang.CharSequence deliveryPlace;
    private long creationTime;
    private java.lang.CharSequence shipmentNumber;
    private java.lang.CharSequence transportationMode;
    private java.lang.CharSequence shipmentTrackingStatus;
    private java.lang.Long edd;
    private java.lang.Long completionTime;
    private java.lang.CharSequence externalShipmentId;
    private java.lang.CharSequence shipmentType;

    /** Creates a new Builder */
    private Builder() {
      super(repositories.Shipment.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(repositories.Shipment.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.shipmentId)) {
        this.shipmentId = data().deepCopy(fields()[0].schema(), other.shipmentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.pickupPlace)) {
        this.pickupPlace = data().deepCopy(fields()[1].schema(), other.pickupPlace);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.deliveryPlace)) {
        this.deliveryPlace = data().deepCopy(fields()[2].schema(), other.deliveryPlace);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.creationTime)) {
        this.creationTime = data().deepCopy(fields()[3].schema(), other.creationTime);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.shipmentNumber)) {
        this.shipmentNumber = data().deepCopy(fields()[4].schema(), other.shipmentNumber);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.transportationMode)) {
        this.transportationMode = data().deepCopy(fields()[5].schema(), other.transportationMode);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.shipmentTrackingStatus)) {
        this.shipmentTrackingStatus = data().deepCopy(fields()[6].schema(), other.shipmentTrackingStatus);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.edd)) {
        this.edd = data().deepCopy(fields()[7].schema(), other.edd);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.completionTime)) {
        this.completionTime = data().deepCopy(fields()[8].schema(), other.completionTime);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.externalShipmentId)) {
        this.externalShipmentId = data().deepCopy(fields()[9].schema(), other.externalShipmentId);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.shipmentType)) {
        this.shipmentType = data().deepCopy(fields()[10].schema(), other.shipmentType);
        fieldSetFlags()[10] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Shipment instance */
    private Builder(repositories.Shipment other) {
            super(repositories.Shipment.SCHEMA$);
      if (isValidValue(fields()[0], other.shipmentId)) {
        this.shipmentId = data().deepCopy(fields()[0].schema(), other.shipmentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.pickupPlace)) {
        this.pickupPlace = data().deepCopy(fields()[1].schema(), other.pickupPlace);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.deliveryPlace)) {
        this.deliveryPlace = data().deepCopy(fields()[2].schema(), other.deliveryPlace);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.creationTime)) {
        this.creationTime = data().deepCopy(fields()[3].schema(), other.creationTime);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.shipmentNumber)) {
        this.shipmentNumber = data().deepCopy(fields()[4].schema(), other.shipmentNumber);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.transportationMode)) {
        this.transportationMode = data().deepCopy(fields()[5].schema(), other.transportationMode);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.shipmentTrackingStatus)) {
        this.shipmentTrackingStatus = data().deepCopy(fields()[6].schema(), other.shipmentTrackingStatus);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.edd)) {
        this.edd = data().deepCopy(fields()[7].schema(), other.edd);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.completionTime)) {
        this.completionTime = data().deepCopy(fields()[8].schema(), other.completionTime);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.externalShipmentId)) {
        this.externalShipmentId = data().deepCopy(fields()[9].schema(), other.externalShipmentId);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.shipmentType)) {
        this.shipmentType = data().deepCopy(fields()[10].schema(), other.shipmentType);
        fieldSetFlags()[10] = true;
      }
    }

    /** Gets the value of the 'shipmentId' field */
    public java.lang.CharSequence getShipmentId() {
      return shipmentId;
    }
    
    /** Sets the value of the 'shipmentId' field */
    public repositories.Shipment.Builder setShipmentId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.shipmentId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'shipmentId' field has been set */
    public boolean hasShipmentId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'shipmentId' field */
    public repositories.Shipment.Builder clearShipmentId() {
      shipmentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'pickupPlace' field */
    public java.lang.CharSequence getPickupPlace() {
      return pickupPlace;
    }
    
    /** Sets the value of the 'pickupPlace' field */
    public repositories.Shipment.Builder setPickupPlace(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.pickupPlace = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'pickupPlace' field has been set */
    public boolean hasPickupPlace() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'pickupPlace' field */
    public repositories.Shipment.Builder clearPickupPlace() {
      pickupPlace = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'deliveryPlace' field */
    public java.lang.CharSequence getDeliveryPlace() {
      return deliveryPlace;
    }
    
    /** Sets the value of the 'deliveryPlace' field */
    public repositories.Shipment.Builder setDeliveryPlace(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.deliveryPlace = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'deliveryPlace' field has been set */
    public boolean hasDeliveryPlace() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'deliveryPlace' field */
    public repositories.Shipment.Builder clearDeliveryPlace() {
      deliveryPlace = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'creationTime' field */
    public java.lang.Long getCreationTime() {
      return creationTime;
    }
    
    /** Sets the value of the 'creationTime' field */
    public repositories.Shipment.Builder setCreationTime(long value) {
      validate(fields()[3], value);
      this.creationTime = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'creationTime' field has been set */
    public boolean hasCreationTime() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'creationTime' field */
    public repositories.Shipment.Builder clearCreationTime() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'shipmentNumber' field */
    public java.lang.CharSequence getShipmentNumber() {
      return shipmentNumber;
    }
    
    /** Sets the value of the 'shipmentNumber' field */
    public repositories.Shipment.Builder setShipmentNumber(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.shipmentNumber = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'shipmentNumber' field has been set */
    public boolean hasShipmentNumber() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'shipmentNumber' field */
    public repositories.Shipment.Builder clearShipmentNumber() {
      shipmentNumber = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'transportationMode' field */
    public java.lang.CharSequence getTransportationMode() {
      return transportationMode;
    }
    
    /** Sets the value of the 'transportationMode' field */
    public repositories.Shipment.Builder setTransportationMode(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.transportationMode = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'transportationMode' field has been set */
    public boolean hasTransportationMode() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'transportationMode' field */
    public repositories.Shipment.Builder clearTransportationMode() {
      transportationMode = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'shipmentTrackingStatus' field */
    public java.lang.CharSequence getShipmentTrackingStatus() {
      return shipmentTrackingStatus;
    }
    
    /** Sets the value of the 'shipmentTrackingStatus' field */
    public repositories.Shipment.Builder setShipmentTrackingStatus(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.shipmentTrackingStatus = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'shipmentTrackingStatus' field has been set */
    public boolean hasShipmentTrackingStatus() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'shipmentTrackingStatus' field */
    public repositories.Shipment.Builder clearShipmentTrackingStatus() {
      shipmentTrackingStatus = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'edd' field */
    public java.lang.Long getEdd() {
      return edd;
    }
    
    /** Sets the value of the 'edd' field */
    public repositories.Shipment.Builder setEdd(java.lang.Long value) {
      validate(fields()[7], value);
      this.edd = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'edd' field has been set */
    public boolean hasEdd() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'edd' field */
    public repositories.Shipment.Builder clearEdd() {
      edd = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'completionTime' field */
    public java.lang.Long getCompletionTime() {
      return completionTime;
    }
    
    /** Sets the value of the 'completionTime' field */
    public repositories.Shipment.Builder setCompletionTime(java.lang.Long value) {
      validate(fields()[8], value);
      this.completionTime = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'completionTime' field has been set */
    public boolean hasCompletionTime() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'completionTime' field */
    public repositories.Shipment.Builder clearCompletionTime() {
      completionTime = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'externalShipmentId' field */
    public java.lang.CharSequence getExternalShipmentId() {
      return externalShipmentId;
    }
    
    /** Sets the value of the 'externalShipmentId' field */
    public repositories.Shipment.Builder setExternalShipmentId(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.externalShipmentId = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'externalShipmentId' field has been set */
    public boolean hasExternalShipmentId() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'externalShipmentId' field */
    public repositories.Shipment.Builder clearExternalShipmentId() {
      externalShipmentId = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'shipmentType' field */
    public java.lang.CharSequence getShipmentType() {
      return shipmentType;
    }
    
    /** Sets the value of the 'shipmentType' field */
    public repositories.Shipment.Builder setShipmentType(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.shipmentType = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'shipmentType' field has been set */
    public boolean hasShipmentType() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'shipmentType' field */
    public repositories.Shipment.Builder clearShipmentType() {
      shipmentType = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    public Shipment build() {
      try {
        Shipment record = new Shipment();
        record.shipmentId = fieldSetFlags()[0] ? this.shipmentId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.pickupPlace = fieldSetFlags()[1] ? this.pickupPlace : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.deliveryPlace = fieldSetFlags()[2] ? this.deliveryPlace : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.creationTime = fieldSetFlags()[3] ? this.creationTime : (java.lang.Long) defaultValue(fields()[3]);
        record.shipmentNumber = fieldSetFlags()[4] ? this.shipmentNumber : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.transportationMode = fieldSetFlags()[5] ? this.transportationMode : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.shipmentTrackingStatus = fieldSetFlags()[6] ? this.shipmentTrackingStatus : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.edd = fieldSetFlags()[7] ? this.edd : (java.lang.Long) defaultValue(fields()[7]);
        record.completionTime = fieldSetFlags()[8] ? this.completionTime : (java.lang.Long) defaultValue(fields()[8]);
        record.externalShipmentId = fieldSetFlags()[9] ? this.externalShipmentId : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.shipmentType = fieldSetFlags()[10] ? this.shipmentType : (java.lang.CharSequence) defaultValue(fields()[10]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
